Add missing dep for GeometricSearchTracker
Resolves linking errors:

    RecoMuonNavigation/MuonNavigationPrinter.o:(.data.rel+0x1758): undefined reference to peinfo for GeometricSearchTracker'
    RecoMuonNavigation/MuonNavigationPrinter.o:(.data.rel+0x1ed8): undefined reference to peinfo for GeometricSearchTracker'
    RecoMuonNavigation/MuonNavigationPrinter.o:(.data.rel+0x2498): undefined reference to peinfo for GeometricSearchTracker'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>