[GCC 11] Fix "this pointer is null" in RecoJets/JetProducers
Log file: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc11/CMSSW_12_1_X_2021-08-02-1100/RecoJets/JetProducers
Error message:
```
In function 'constexpr decltype (t1.eta()) reco::deltaR2(const T1&, const T2&) [with T1 = reco::Jet; T2 = reco::Candidate]',
    inlined from 'constexpr decltype (t1.eta()) reco::deltaR(const T1&, const T2&) [with T1 = reco::Jet; T2 = reco::Candidate]' at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/DataFormats/Math/interface/deltaR.h:31:21,
    inlined from 'PileupJetIdentifier PileupJetIdAlgo::computeIdVariables(const reco::Jet*, float, const reco::Vertex*, const VertexCollection&, double, bool)' at /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/RecoJets/JetProducers/src/PileupJetIdAlgo.cc:668:42:
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/DataFormats/Math/interface/deltaR.h:19:22: error: 'this' pointer is null [-Werror=nonnull]
    19 |     Float p2 = t2.phi();
      |                ~~~~~~^~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e3e3f354f3bbc00899d20eeb240b2272/opt/cmssw/slc7_amd64_gcc11/cms/cmssw/CMSSW_12_1_X_2021-08-02-1100/src/DataFormats/Math/interface/deltaR.h:21:22: error: 'this' pointer is null [-Werror=nonnull]
    21 |     Float e2 = t2.eta();
      |                ~~~~~~^~
```