Add missing dependency for GeometricSearchDet
Resolves linking errors:

    TrackingToolsMeasurementDet/LayerMeasurements.o:(.data.rel+0xb18): undefined reference to peinfo for GeometricSearchDet'
    TrackingToolsMeasurementDet/LayerMeasurements.o:(.data.rel+0x2098): undefined reference to peinfo for GeometricSearchDet'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>