Add missing dependency for edm::TRandomAdaptor
Resolves linking errors:

    SimTransportHectorProducer/HectorProducer.o:(.data.rel+0x1b98): undefined reference to peinfo for edm::TRandomAdaptor'
    SimTransportHectorProducer/HectorProducer.o:(.data.rel+0x1bd8): undefined reference to peinfo for edm::TRandomAdaptor'
    SimTransportHectorProducer/CTPPSHectorProducer.o:(.data.rel+0x1598): undefined reference to peinfo for edm::TRandomAdaptor'
    SimTransportHectorProducer/CTPPSHectorProducer.o:(.data.rel+0x15d8): undefined reference to peinfo for edm::TRandomAdaptor'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>