Add missing dep for MuonDetLayerGeometry, GeometricSearchTracker
Resolves linking errors:

    TrackingToolsRecoGeometry/GlobalDetLayerGeometry.o:(.data.rel+0xd8): undefined reference to peinfo for MuonDetLayerGeometry'
    TrackingToolsRecoGeometry/GlobalDetLayerGeometry.o:(.data.rel+0x158): undefined reference to peinfo for GeometricSearchTracker'

Signed-off-by: David Abdurachmanov <David.Abdurachmanov@cern.ch>